### PR TITLE
manifets: Track Updated display hals sm8350

### PR DESCRIPTION
**Pull request by dominator-prime**
Change-Id: I0bb6982e96118c4a2a9b9660254be381cd1e53fd
Signed-off-by: aswin7469 <aswinas@pixysos.com>
Signed-off-by: optimus9811 <vikasyaduvanshi@gmail.com>

### CODE REVIEW

**Comment by Joker-V2** [comment]
https://github.com/SuperiorOS/manifest/commit/fe935dcb2eb08b3a59a7f3d97dce4c6fe325be8f

**Comment by dominator-prime** [comment]
you forgot [this ](https://github.com/SuperiorOS/manifest/pull/15/commits/949f59e8234582606089c7a9ec2c6568aefa8446#diff-899a321839c42023ee906fc64cb48c5a50aa2405db615b4d6226d5681f949b52L96)   and [this](https://github.com/SuperiorOS/manifest/pull/15/commits/949f59e8234582606089c7a9ec2c6568aefa8446#diff-93368de740104705b6827502dd5503e81dbf2ddf7e3fe3db4957fd23cf45b4aaR32)

display and audio updated hals

**Comment by Joker-V2** [comment]
Doing man.. wait.. pushing repos

**Comment by dominator-prime** [comment]
just telling :))

**Pull request closed without merging**
